config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/info', to: 'static_pages#info'
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.railstutorial.org/">神月运维专用</a>
		by <a href="http://www.michaelhartl.com/">ZeZe</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "关于", about_path %></li>
			<li><%= link_to "联系我们", contact_path %></li>
			<li><a href="https://www.shineyue.com/">新闻</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "神月软件运维部", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "主页",  root_path %></li>
        <li><%= link_to "帮助",  help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "用户列表", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              账户 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "个人资料", current_user %></li>
              <li><%= link_to "设置", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "退出登录", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
         <li><%= link_to "登录",  login_path %></li>
        <% end %>
        <!-- <li><a href="#">Home</a></li> -->
      </ul>
    </nav>
</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<!-- stylesheet_link_tag方法，传入两个参数：一个字符串，指明样式的路径;
     另一个是散列，包含两个元素，第一个指明媒介类型，第二个启用Turbolink功能 
<link data-turbolinks-track="true" href="/assets/application.css" media="all"
rel="stylesheet" />。 -->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  		<%= yield %>
  		<%= render 'layouts/footer' %>
      <!--<%= debug(params) if Rails.env.development? %> -->
      <br/>
  	</div>
  </body>
</html>